### ISSUE TITLE
Currently, there is a problem with the API and because of that we can't use it in production.

### ISSUE THREAD

**Issue by NomanBaigA** [mbakgun/midjourney-images-compose-multiplatform#57]
Because API is taking images from Midjourney sometimes we got nude images or images which is not allowed in the production. 

It will be really great if we found a way to filter out those images

**Comment by mbakgun** [comment]
Hello, could you send me an example of the picture that you accept as a nude example? I have been actively developing and looking at pictures for a while, but I haven't come across a picture that is clearly nude. , They don't allow this on their platform.

**Comment by NomanBaigA** [comment]
> Hello, could you send me an example of the picture that you accept as a nude example? I have been actively developing and looking at pictures for a while, but I haven't come across a picture that is clearly nude. , They don't allow this on their platform.

Sure, I will collect some and share them with you. And yes those pictures are rare but they can cause issues with play console

**Comment by mbakgun** [comment]
I understand your concerns. At the moment, I don't have any recommendations or workarounds for this, but it is technically possible, given the existing prompts on the website. I may consider adding functionalities such as tag selection or something similar in the future.

**Comment by NomanBaigA** [comment]
> I understand your concerns. At the moment, I don't have any recommendations or workarounds for this, but it is technically possible, given the existing prompts on the website. I may consider adding functionalities such as tag selection or something similar in the future.

Maybe prompt will help like if prompt contains some specific words then API ignore that particular image. I don't know if it's possible

**Comment by NomanBaigA** [comment]
> I understand your concerns. At the moment, I don't have any recommendations or workarounds for this, but it is technically possible, given the existing prompts on the website. I may consider adding functionalities such as tag selection or something similar in the future.

Is the problem solved?

**Comment by mbakgun** [comment]
In the near future, no enhancements are planned, especially for the API side. The issue has been closed for now.

**Comment by NomanBaigA** [comment]
> In the near future, no enhancements are planned, especially for the API side. The issue has been closed for now.

Look I was talking about this kind of images.

Screenshot - 

![Screenshot_2023-08-01](https://github.com/mbakgun/midjourney-images-compose-multiplatform/assets/49509445/8c8ede73-495c-4c64-ac38-33ff2a0717f4)
