### ISSUE TITLE
Project not get build Caused by: org.gradle.api.internal.plugins.PluginApplicationException

### ISSUE THREAD

**Issue by mirzaalipro** [mbakgun/midjourney-images-compose-multiplatform#77]
org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'com.android.internal.application'

<img width="1680" alt="Screenshot 2023-08-17 at 5 21 33 PM" src="https://github.com/mbakgun/midjourney-images-compose-multiplatform/assets/121868603/8f337b52-f9c7-4feb-af12-aad04a6a37f7">

**Comment by mbakgun** [comment]
Hi @mirzaalipro, the project is actually buildable. Please see previously succedeed [Github CI actions](https://github.com/mbakgun/midjourney-images-compose-multiplatform/actions?query=is%3Asuccess). I suggest that you check your system using Kdoctor. This topic has been detailed in the medium article.

**Comment by mirzaalipro** [comment]
<img width="611" alt="Screenshot 2023-08-21 at 12 06 59 PM" src="https://github.com/mbakgun/midjourney-images-compose-multiplatform/assets/121868603/dbc47001-1295-42b8-ab05-5580e496ed0b">
